/**
 * Every notification kind Phase 16 generates: eight event-driven (dispatched off the exact
 * `domain_events` row that caused them, or — for `training.assigned` — off the assignment-creation
 * call site directly, since `training.assignment_batch_created`'s event has no per-employee
 * subject) plus three time-derived (`due_soon`/`overdue`/`expiring_soon`, generated by the
 * reconcile pass in `src/server/notifications/service.ts`). Defined here rather than in
 * `service.ts` so this module has no import from it — `service.ts` imports the type and label
 * data from here instead, avoiding a cycle.
 */
export type NotificationType =
  | "training.assigned"
  | "training.awaiting_approval"
  | "training.completed"
  | "training.approval_decided"
  | "training.due_soon"
  | "training.overdue"
  | "qualification.awarded"
  | "qualification.revoked"
  | "qualification.expiring_soon"
  | "checklist_run.awaiting_approval"
  | "checklist_run.approval_decided";

export const notificationTypeValues: readonly NotificationType[] = [
  "training.assigned",
  "training.awaiting_approval",
  "training.completed",
  "training.approval_decided",
  "training.due_soon",
  "training.overdue",
  "qualification.awarded",
  "qualification.revoked",
  "qualification.expiring_soon",
  "checklist_run.awaiting_approval",
  "checklist_run.approval_decided",
];

/**
 * Human titles per notification type, the same "type is the resolvable key" convention
 * `ACTIVITY_TYPE_LABELS` already uses for `domain_events.type` — see
 * `src/components/management/activity-labels.ts`. Reused for both the in-app list UI and the
 * SMTP email subject line, so title text only lives in one place.
 */
export const NOTIFICATION_TYPE_LABELS: Record<NotificationType, string> = {
  "training.assigned": "New training assigned",
  "training.awaiting_approval": "Training submission awaiting review",
  "training.completed": "Training completed",
  "training.approval_decided": "Training approval decided",
  "training.due_soon": "Training due soon",
  "training.overdue": "Training overdue",
  "qualification.awarded": "Qualification awarded",
  "qualification.revoked": "Qualification revoked",
  "qualification.expiring_soon": "Qualification expiring soon",
  "checklist_run.awaiting_approval": "Checklist run awaiting review",
  "checklist_run.approval_decided": "Checklist approval decided",
};

/**
 * Turns a notification's safe `params` into a short human sentence for the list UI and the email
 * body. Every branch only reads params this module's own callers actually write (see
 * `src/server/notifications/service.ts`), so an unexpected shape falls back to the bare title
 * rather than throwing.
 */
export function formatNotificationBody(
  type: NotificationType,
  params: Record<string, string | number | boolean | null>,
): string {
  const sopTitle = typeof params["sopTitle"] === "string" ? params["sopTitle"] : "";
  const employeeName = typeof params["employeeName"] === "string" ? params["employeeName"] : "";
  const definitionName =
    typeof params["definitionName"] === "string" ? params["definitionName"] : "";
  const checklistTitle =
    typeof params["checklistTitle"] === "string" ? params["checklistTitle"] : "";
  const decision = typeof params["decision"] === "string" ? params["decision"] : "";
  const status = typeof params["status"] === "string" ? params["status"] : "";
  const dueDate = typeof params["dueDate"] === "string" ? params["dueDate"] : "";

  switch (type) {
    case "training.assigned":
      return sopTitle;
    case "training.awaiting_approval":
      return [employeeName, sopTitle].filter(Boolean).join(" — ");
    case "training.completed":
      return [sopTitle, status].filter(Boolean).join(" — ");
    case "training.approval_decided":
      return [sopTitle, decision.replace(/_/g, " ")].filter(Boolean).join(" — ");
    case "training.due_soon":
    case "training.overdue":
      return [sopTitle, dueDate ? `due ${dueDate}` : ""].filter(Boolean).join(" — ");
    case "qualification.awarded":
    case "qualification.revoked":
      return definitionName;
    case "qualification.expiring_soon":
      return [definitionName, dueDate ? `expires ${dueDate}` : ""].filter(Boolean).join(" — ");
    case "checklist_run.awaiting_approval":
      return [employeeName, checklistTitle].filter(Boolean).join(" — ");
    case "checklist_run.approval_decided":
      return [checklistTitle, decision.replace(/_/g, " ")].filter(Boolean).join(" — ");
    default:
      return "";
  }
}

export function resolveNotificationText(
  type: NotificationType,
  params: Record<string, string | number | boolean | null>,
): { title: string; body: string } {
  return { title: NOTIFICATION_TYPE_LABELS[type], body: formatNotificationBody(type, params) };
}
